# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d88ef046b5b0470cb4c64dc2fb82653d73178d5ce929697b7d2deba01e5ebcaf39a45aac99d05b26a42b31e570edd3cc1f886d29de0e10d918045b24c6fa9afa

test:
  secret_key_base: 4688f4a79445a71bfec406434fe374a0b82a714dce96c530ed5c718d8a4e7849ab20d748eb7c43c9af02adeab0aac386bbe41dcc0b3387c195e977d3eed41eb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
